version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: unless-stopped
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.soject.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        # Add GitLab resource optimizations
        unicorn['worker_processes'] = 2
        unicorn['worker_timeout'] = 60
        postgresql['shared_buffers'] = "256MB"
        redis['maxmemory'] = "256MB"
        redis['maxmemory_policy'] = "allkeys-lru"
    ports:
      - '8081:80'      # Web UI
      - '443:443'      # HTTPS (optional, can be mapped)
      - '2224:22'      # SSH
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/backups:/var/opt/gitlab/backups
    depends_on:
      - redis
      - postgres
    healthcheck:
      test: ["CMD", "/opt/gitlab/bin/gitlab-healthcheck", "--fail"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 2m
    networks:
      - gitlab_network
      - web_network
    # Add resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G

  redis:
    image: redis:7-alpine
    container_name: gitlab-redis
    restart: unless-stopped
    volumes:
      - ./gitlab/redis:/data
    networks:
      - gitlab_network
    # Add resource limits for Redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  postgres:
    image: postgres:15
    container_name: gitlab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gitlabhq_production
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlabpass
      # Add PostgreSQL optimizations
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
      POSTGRES_WORK_MEM: 4MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
    volumes:
      - ./gitlab/postgres:/var/lib/postgresql/data
    networks:
      - gitlab_network
    # Add resource limits for PostgreSQL
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_redis_data:
  gitlab_postgres_data:

networks:
  gitlab_network:
    driver: bridge
  web_network:
    external: true
    name: web_network 