version: '3.8'

services:
  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/mime.types:/etc/nginx/mime.types:ro
      - ./config/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./logs:/var/log/nginx
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge 