version: '3.8'

services:
  web-app:
    build: .
    container_name: web-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=myapp
      - DB_USER=myapp_user
      - DB_PASSWORD=myapp_password
    volumes:
      - ./logs:/app/logs
    networks:
      - web_network

networks:
  web_network:
    external: true
    name: web_network 